package com.example.domain;

import java.util.Date;

public class DailyReport {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daily_reports.id
     *
     * @mbggenerated Wed Nov 11 00:18:58 JST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daily_reports.user_id
     *
     * @mbggenerated Wed Nov 11 00:18:58 JST 2020
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daily_reports.todo_id
     *
     * @mbggenerated Wed Nov 11 00:18:58 JST 2020
     */
    private Integer todoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daily_reports.today_report
     *
     * @mbggenerated Wed Nov 11 00:18:58 JST 2020
     */
    private String todayReport;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daily_reports.level_achievementlevel_achievement
     *
     * @mbggenerated Wed Nov 11 00:18:58 JST 2020
     */
    private Integer levelAchievementlevelAchievement;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daily_reports.impressions
     *
     * @mbggenerated Wed Nov 11 00:18:58 JST 2020
     */
    private String impressions;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daily_reports.registration_date
     *
     * @mbggenerated Wed Nov 11 00:18:58 JST 2020
     */
    private Date registrationDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_reports.id
     *
     * @return the value of daily_reports.id
     *
     * @mbggenerated Wed Nov 11 00:18:58 JST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_reports.id
     *
     * @param id the value for daily_reports.id
     *
     * @mbggenerated Wed Nov 11 00:18:58 JST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_reports.user_id
     *
     * @return the value of daily_reports.user_id
     *
     * @mbggenerated Wed Nov 11 00:18:58 JST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_reports.user_id
     *
     * @param userId the value for daily_reports.user_id
     *
     * @mbggenerated Wed Nov 11 00:18:58 JST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_reports.todo_id
     *
     * @return the value of daily_reports.todo_id
     *
     * @mbggenerated Wed Nov 11 00:18:58 JST 2020
     */
    public Integer getTodoId() {
        return todoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_reports.todo_id
     *
     * @param todoId the value for daily_reports.todo_id
     *
     * @mbggenerated Wed Nov 11 00:18:58 JST 2020
     */
    public void setTodoId(Integer todoId) {
        this.todoId = todoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_reports.today_report
     *
     * @return the value of daily_reports.today_report
     *
     * @mbggenerated Wed Nov 11 00:18:58 JST 2020
     */
    public String getTodayReport() {
        return todayReport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_reports.today_report
     *
     * @param todayReport the value for daily_reports.today_report
     *
     * @mbggenerated Wed Nov 11 00:18:58 JST 2020
     */
    public void setTodayReport(String todayReport) {
        this.todayReport = todayReport == null ? null : todayReport.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_reports.level_achievementlevel_achievement
     *
     * @return the value of daily_reports.level_achievementlevel_achievement
     *
     * @mbggenerated Wed Nov 11 00:18:58 JST 2020
     */
    public Integer getLevelAchievementlevelAchievement() {
        return levelAchievementlevelAchievement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_reports.level_achievementlevel_achievement
     *
     * @param levelAchievementlevelAchievement the value for daily_reports.level_achievementlevel_achievement
     *
     * @mbggenerated Wed Nov 11 00:18:58 JST 2020
     */
    public void setLevelAchievementlevelAchievement(Integer levelAchievementlevelAchievement) {
        this.levelAchievementlevelAchievement = levelAchievementlevelAchievement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_reports.impressions
     *
     * @return the value of daily_reports.impressions
     *
     * @mbggenerated Wed Nov 11 00:18:58 JST 2020
     */
    public String getImpressions() {
        return impressions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_reports.impressions
     *
     * @param impressions the value for daily_reports.impressions
     *
     * @mbggenerated Wed Nov 11 00:18:58 JST 2020
     */
    public void setImpressions(String impressions) {
        this.impressions = impressions == null ? null : impressions.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_reports.registration_date
     *
     * @return the value of daily_reports.registration_date
     *
     * @mbggenerated Wed Nov 11 00:18:58 JST 2020
     */
    public Date getRegistrationDate() {
        return registrationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_reports.registration_date
     *
     * @param registrationDate the value for daily_reports.registration_date
     *
     * @mbggenerated Wed Nov 11 00:18:58 JST 2020
     */
    public void setRegistrationDate(Date registrationDate) {
        this.registrationDate = registrationDate;
    }
}