package com.example.domain;

public class Following {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column followings.id
     *
     * @mbggenerated Wed Nov 11 00:25:22 JST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column followings.follow_flag
     *
     * @mbggenerated Wed Nov 11 00:25:22 JST 2020
     */
    private Boolean followFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column followings.following_id
     *
     * @mbggenerated Wed Nov 11 00:25:22 JST 2020
     */
    private Integer followingId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column followings.followed_id
     *
     * @mbggenerated Wed Nov 11 00:25:22 JST 2020
     */
    private Integer followedId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column followings.id
     *
     * @return the value of followings.id
     *
     * @mbggenerated Wed Nov 11 00:25:22 JST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column followings.id
     *
     * @param id the value for followings.id
     *
     * @mbggenerated Wed Nov 11 00:25:22 JST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column followings.follow_flag
     *
     * @return the value of followings.follow_flag
     *
     * @mbggenerated Wed Nov 11 00:25:22 JST 2020
     */
    public Boolean getFollowFlag() {
        return followFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column followings.follow_flag
     *
     * @param followFlag the value for followings.follow_flag
     *
     * @mbggenerated Wed Nov 11 00:25:22 JST 2020
     */
    public void setFollowFlag(Boolean followFlag) {
        this.followFlag = followFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column followings.following_id
     *
     * @return the value of followings.following_id
     *
     * @mbggenerated Wed Nov 11 00:25:22 JST 2020
     */
    public Integer getFollowingId() {
        return followingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column followings.following_id
     *
     * @param followingId the value for followings.following_id
     *
     * @mbggenerated Wed Nov 11 00:25:22 JST 2020
     */
    public void setFollowingId(Integer followingId) {
        this.followingId = followingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column followings.followed_id
     *
     * @return the value of followings.followed_id
     *
     * @mbggenerated Wed Nov 11 00:25:22 JST 2020
     */
    public Integer getFollowedId() {
        return followedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column followings.followed_id
     *
     * @param followedId the value for followings.followed_id
     *
     * @mbggenerated Wed Nov 11 00:25:22 JST 2020
     */
    public void setFollowedId(Integer followedId) {
        this.followedId = followedId;
    }
}