package com.example.domain;

import java.util.Date;

public class MonthlyReport {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monthly_reports.id
     *
     * @mbggenerated Thu Jan 21 17:21:05 JST 2021
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monthly_reports.user_id
     *
     * @mbggenerated Thu Jan 21 17:21:05 JST 2021
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monthly_reports.this_month_objective_id
     *
     * @mbggenerated Thu Jan 21 17:21:05 JST 2021
     */
    private Integer thisMonthObjectiveId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monthly_reports.impressions
     *
     * @mbggenerated Thu Jan 21 17:21:05 JST 2021
     */
    private String impressions;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monthly_reports.next_month_objective_id
     *
     * @mbggenerated Thu Jan 21 17:21:05 JST 2021
     */
    private Integer nextMonthObjectiveId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monthly_reports.registration_date
     *
     * @mbggenerated Thu Jan 21 17:21:05 JST 2021
     */
    private Date registrationDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monthly_reports.id
     *
     * @return the value of monthly_reports.id
     *
     * @mbggenerated Thu Jan 21 17:21:05 JST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monthly_reports.id
     *
     * @param id the value for monthly_reports.id
     *
     * @mbggenerated Thu Jan 21 17:21:05 JST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monthly_reports.user_id
     *
     * @return the value of monthly_reports.user_id
     *
     * @mbggenerated Thu Jan 21 17:21:05 JST 2021
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monthly_reports.user_id
     *
     * @param userId the value for monthly_reports.user_id
     *
     * @mbggenerated Thu Jan 21 17:21:05 JST 2021
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monthly_reports.this_month_objective_id
     *
     * @return the value of monthly_reports.this_month_objective_id
     *
     * @mbggenerated Thu Jan 21 17:21:05 JST 2021
     */
    public Integer getThisMonthObjectiveId() {
        return thisMonthObjectiveId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monthly_reports.this_month_objective_id
     *
     * @param thisMonthObjectiveId the value for monthly_reports.this_month_objective_id
     *
     * @mbggenerated Thu Jan 21 17:21:05 JST 2021
     */
    public void setThisMonthObjectiveId(Integer thisMonthObjectiveId) {
        this.thisMonthObjectiveId = thisMonthObjectiveId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monthly_reports.impressions
     *
     * @return the value of monthly_reports.impressions
     *
     * @mbggenerated Thu Jan 21 17:21:05 JST 2021
     */
    public String getImpressions() {
        return impressions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monthly_reports.impressions
     *
     * @param impressions the value for monthly_reports.impressions
     *
     * @mbggenerated Thu Jan 21 17:21:05 JST 2021
     */
    public void setImpressions(String impressions) {
        this.impressions = impressions == null ? null : impressions.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monthly_reports.next_month_objective_id
     *
     * @return the value of monthly_reports.next_month_objective_id
     *
     * @mbggenerated Thu Jan 21 17:21:05 JST 2021
     */
    public Integer getNextMonthObjectiveId() {
        return nextMonthObjectiveId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monthly_reports.next_month_objective_id
     *
     * @param nextMonthObjectiveId the value for monthly_reports.next_month_objective_id
     *
     * @mbggenerated Thu Jan 21 17:21:05 JST 2021
     */
    public void setNextMonthObjectiveId(Integer nextMonthObjectiveId) {
        this.nextMonthObjectiveId = nextMonthObjectiveId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monthly_reports.registration_date
     *
     * @return the value of monthly_reports.registration_date
     *
     * @mbggenerated Thu Jan 21 17:21:05 JST 2021
     */
    public Date getRegistrationDate() {
        return registrationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monthly_reports.registration_date
     *
     * @param registrationDate the value for monthly_reports.registration_date
     *
     * @mbggenerated Thu Jan 21 17:21:05 JST 2021
     */
    public void setRegistrationDate(Date registrationDate) {
        this.registrationDate = registrationDate;
    }
}