package com.example.domain;

import java.util.Date;

public class MonthlyReports {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monthly_reports.id
     *
     * @mbggenerated Wed Nov 11 00:21:20 JST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monthly_reports.user_id
     *
     * @mbggenerated Wed Nov 11 00:21:20 JST 2020
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monthly_reports.objective_id
     *
     * @mbggenerated Wed Nov 11 00:21:20 JST 2020
     */
    private Integer objectiveId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monthly_reports.this_month_objective
     *
     * @mbggenerated Wed Nov 11 00:21:20 JST 2020
     */
    private String thisMonthObjective;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monthly_reports.impressions
     *
     * @mbggenerated Wed Nov 11 00:21:20 JST 2020
     */
    private String impressions;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monthly_reports.next_month_objective
     *
     * @mbggenerated Wed Nov 11 00:21:20 JST 2020
     */
    private String nextMonthObjective;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monthly_reports.registration_date
     *
     * @mbggenerated Wed Nov 11 00:21:20 JST 2020
     */
    private Date registrationDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monthly_reports.id
     *
     * @return the value of monthly_reports.id
     *
     * @mbggenerated Wed Nov 11 00:21:20 JST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monthly_reports.id
     *
     * @param id the value for monthly_reports.id
     *
     * @mbggenerated Wed Nov 11 00:21:20 JST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monthly_reports.user_id
     *
     * @return the value of monthly_reports.user_id
     *
     * @mbggenerated Wed Nov 11 00:21:20 JST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monthly_reports.user_id
     *
     * @param userId the value for monthly_reports.user_id
     *
     * @mbggenerated Wed Nov 11 00:21:20 JST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monthly_reports.objective_id
     *
     * @return the value of monthly_reports.objective_id
     *
     * @mbggenerated Wed Nov 11 00:21:20 JST 2020
     */
    public Integer getObjectiveId() {
        return objectiveId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monthly_reports.objective_id
     *
     * @param objectiveId the value for monthly_reports.objective_id
     *
     * @mbggenerated Wed Nov 11 00:21:20 JST 2020
     */
    public void setObjectiveId(Integer objectiveId) {
        this.objectiveId = objectiveId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monthly_reports.this_month_objective
     *
     * @return the value of monthly_reports.this_month_objective
     *
     * @mbggenerated Wed Nov 11 00:21:20 JST 2020
     */
    public String getThisMonthObjective() {
        return thisMonthObjective;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monthly_reports.this_month_objective
     *
     * @param thisMonthObjective the value for monthly_reports.this_month_objective
     *
     * @mbggenerated Wed Nov 11 00:21:20 JST 2020
     */
    public void setThisMonthObjective(String thisMonthObjective) {
        this.thisMonthObjective = thisMonthObjective == null ? null : thisMonthObjective.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monthly_reports.impressions
     *
     * @return the value of monthly_reports.impressions
     *
     * @mbggenerated Wed Nov 11 00:21:20 JST 2020
     */
    public String getImpressions() {
        return impressions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monthly_reports.impressions
     *
     * @param impressions the value for monthly_reports.impressions
     *
     * @mbggenerated Wed Nov 11 00:21:20 JST 2020
     */
    public void setImpressions(String impressions) {
        this.impressions = impressions == null ? null : impressions.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monthly_reports.next_month_objective
     *
     * @return the value of monthly_reports.next_month_objective
     *
     * @mbggenerated Wed Nov 11 00:21:20 JST 2020
     */
    public String getNextMonthObjective() {
        return nextMonthObjective;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monthly_reports.next_month_objective
     *
     * @param nextMonthObjective the value for monthly_reports.next_month_objective
     *
     * @mbggenerated Wed Nov 11 00:21:20 JST 2020
     */
    public void setNextMonthObjective(String nextMonthObjective) {
        this.nextMonthObjective = nextMonthObjective == null ? null : nextMonthObjective.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monthly_reports.registration_date
     *
     * @return the value of monthly_reports.registration_date
     *
     * @mbggenerated Wed Nov 11 00:21:20 JST 2020
     */
    public Date getRegistrationDate() {
        return registrationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monthly_reports.registration_date
     *
     * @param registrationDate the value for monthly_reports.registration_date
     *
     * @mbggenerated Wed Nov 11 00:21:20 JST 2020
     */
    public void setRegistrationDate(Date registrationDate) {
        this.registrationDate = registrationDate;
    }
}