package com.example.domain;

import java.util.Date;

public class Objective {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column objectives.id
     *
     * @mbggenerated Wed Nov 11 00:23:40 JST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column objectives.user_id
     *
     * @mbggenerated Wed Nov 11 00:23:40 JST 2020
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column objectives.objective
     *
     * @mbggenerated Wed Nov 11 00:23:40 JST 2020
     */
    private String objective;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column objectives.objective_month
     *
     * @mbggenerated Wed Nov 11 00:23:40 JST 2020
     */
    private Date objectiveMonth;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column objectives.id
     *
     * @return the value of objectives.id
     *
     * @mbggenerated Wed Nov 11 00:23:40 JST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column objectives.id
     *
     * @param id the value for objectives.id
     *
     * @mbggenerated Wed Nov 11 00:23:40 JST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column objectives.user_id
     *
     * @return the value of objectives.user_id
     *
     * @mbggenerated Wed Nov 11 00:23:40 JST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column objectives.user_id
     *
     * @param userId the value for objectives.user_id
     *
     * @mbggenerated Wed Nov 11 00:23:40 JST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column objectives.objective
     *
     * @return the value of objectives.objective
     *
     * @mbggenerated Wed Nov 11 00:23:40 JST 2020
     */
    public String getObjective() {
        return objective;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column objectives.objective
     *
     * @param objective the value for objectives.objective
     *
     * @mbggenerated Wed Nov 11 00:23:40 JST 2020
     */
    public void setObjective(String objective) {
        this.objective = objective == null ? null : objective.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column objectives.objective_month
     *
     * @return the value of objectives.objective_month
     *
     * @mbggenerated Wed Nov 11 00:23:40 JST 2020
     */
    public Date getObjectiveMonth() {
        return objectiveMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column objectives.objective_month
     *
     * @param objectiveMonth the value for objectives.objective_month
     *
     * @mbggenerated Wed Nov 11 00:23:40 JST 2020
     */
    public void setObjectiveMonth(Date objectiveMonth) {
        this.objectiveMonth = objectiveMonth;
    }
}