package com.example.domain;

import java.util.Date;

public class Todo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todoes.id
     *
     * @mbggenerated Wed Nov 11 00:15:42 JST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todoes.user_id
     *
     * @mbggenerated Wed Nov 11 00:15:42 JST 2020
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todoes.task
     *
     * @mbggenerated Wed Nov 11 00:15:42 JST 2020
     */
    private String task;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todoes.status
     *
     * @mbggenerated Wed Nov 11 00:15:42 JST 2020
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todoes.registration_date
     *
     * @mbggenerated Wed Nov 11 00:15:42 JST 2020
     */
    private Date registrationDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todoes.id
     *
     * @return the value of todoes.id
     *
     * @mbggenerated Wed Nov 11 00:15:42 JST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todoes.id
     *
     * @param id the value for todoes.id
     *
     * @mbggenerated Wed Nov 11 00:15:42 JST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todoes.user_id
     *
     * @return the value of todoes.user_id
     *
     * @mbggenerated Wed Nov 11 00:15:42 JST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todoes.user_id
     *
     * @param userId the value for todoes.user_id
     *
     * @mbggenerated Wed Nov 11 00:15:42 JST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todoes.task
     *
     * @return the value of todoes.task
     *
     * @mbggenerated Wed Nov 11 00:15:42 JST 2020
     */
    public String getTask() {
        return task;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todoes.task
     *
     * @param task the value for todoes.task
     *
     * @mbggenerated Wed Nov 11 00:15:42 JST 2020
     */
    public void setTask(String task) {
        this.task = task == null ? null : task.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todoes.status
     *
     * @return the value of todoes.status
     *
     * @mbggenerated Wed Nov 11 00:15:42 JST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todoes.status
     *
     * @param status the value for todoes.status
     *
     * @mbggenerated Wed Nov 11 00:15:42 JST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todoes.registration_date
     *
     * @return the value of todoes.registration_date
     *
     * @mbggenerated Wed Nov 11 00:15:42 JST 2020
     */
    public Date getRegistrationDate() {
        return registrationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todoes.registration_date
     *
     * @param registrationDate the value for todoes.registration_date
     *
     * @mbggenerated Wed Nov 11 00:15:42 JST 2020
     */
    public void setRegistrationDate(Date registrationDate) {
        this.registrationDate = registrationDate;
    }
}