package com.example.domain;

import java.util.Date;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.id
     *
     * @mbggenerated Tue Nov 10 13:47:56 JST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.name
     *
     * @mbggenerated Tue Nov 10 13:47:56 JST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.continuation_days
     *
     * @mbggenerated Tue Nov 10 13:47:56 JST 2020
     */
    private Integer continuationDays;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.firstday_continuation
     *
     * @mbggenerated Tue Nov 10 13:47:56 JST 2020
     */
    private Date firstdayContinuation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.level_achievement
     *
     * @mbggenerated Tue Nov 10 13:47:56 JST 2020
     */
    private Integer levelAchievement;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.id
     *
     * @return the value of users.id
     *
     * @mbggenerated Tue Nov 10 13:47:56 JST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.id
     *
     * @param id the value for users.id
     *
     * @mbggenerated Tue Nov 10 13:47:56 JST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.name
     *
     * @return the value of users.name
     *
     * @mbggenerated Tue Nov 10 13:47:56 JST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.name
     *
     * @param name the value for users.name
     *
     * @mbggenerated Tue Nov 10 13:47:56 JST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.continuation_days
     *
     * @return the value of users.continuation_days
     *
     * @mbggenerated Tue Nov 10 13:47:56 JST 2020
     */
    public Integer getContinuationDays() {
        return continuationDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.continuation_days
     *
     * @param continuationDays the value for users.continuation_days
     *
     * @mbggenerated Tue Nov 10 13:47:56 JST 2020
     */
    public void setContinuationDays(Integer continuationDays) {
        this.continuationDays = continuationDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.firstday_continuation
     *
     * @return the value of users.firstday_continuation
     *
     * @mbggenerated Tue Nov 10 13:47:56 JST 2020
     */
    public Date getFirstdayContinuation() {
        return firstdayContinuation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.firstday_continuation
     *
     * @param firstdayContinuation the value for users.firstday_continuation
     *
     * @mbggenerated Tue Nov 10 13:47:56 JST 2020
     */
    public void setFirstdayContinuation(Date firstdayContinuation) {
        this.firstdayContinuation = firstdayContinuation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.level_achievement
     *
     * @return the value of users.level_achievement
     *
     * @mbggenerated Tue Nov 10 13:47:56 JST 2020
     */
    public Integer getLevelAchievement() {
        return levelAchievement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.level_achievement
     *
     * @param levelAchievement the value for users.level_achievement
     *
     * @mbggenerated Tue Nov 10 13:47:56 JST 2020
     */
    public void setLevelAchievement(Integer levelAchievement) {
        this.levelAchievement = levelAchievement;
    }
}