package com.example.mapper;

import com.example.domain.DailyReports;
import com.example.domain.DailyReportsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DailyReportsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_reports
     *
     * @mbggenerated Thu Dec 03 10:32:43 JST 2020
     */
    int countByExample(DailyReportsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_reports
     *
     * @mbggenerated Thu Dec 03 10:32:43 JST 2020
     */
    int deleteByExample(DailyReportsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_reports
     *
     * @mbggenerated Thu Dec 03 10:32:43 JST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_reports
     *
     * @mbggenerated Thu Dec 03 10:32:43 JST 2020
     */
    int insert(DailyReports record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_reports
     *
     * @mbggenerated Thu Dec 03 10:32:43 JST 2020
     */
    int insertSelective(DailyReports record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_reports
     *
     * @mbggenerated Thu Dec 03 10:32:43 JST 2020
     */
    List<DailyReports> selectByExample(DailyReportsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_reports
     *
     * @mbggenerated Thu Dec 03 10:32:43 JST 2020
     */
    DailyReports selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_reports
     *
     * @mbggenerated Thu Dec 03 10:32:43 JST 2020
     */
    int updateByExampleSelective(@Param("record") DailyReports record, @Param("example") DailyReportsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_reports
     *
     * @mbggenerated Thu Dec 03 10:32:43 JST 2020
     */
    int updateByExample(@Param("record") DailyReports record, @Param("example") DailyReportsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_reports
     *
     * @mbggenerated Thu Dec 03 10:32:43 JST 2020
     */
    int updateByPrimaryKeySelective(DailyReports record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_reports
     *
     * @mbggenerated Thu Dec 03 10:32:43 JST 2020
     */
    int updateByPrimaryKey(DailyReports record);
}