package com.example.mapper;

import com.example.domain.DailyReport;
import com.example.domain.DailyReportExample;

import java.util.Date;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface DailyReportMapper {

	/**
	 * 日付とユーザーIDで日報を検索する。
	 * 
	 * @param date
	 * @return
	 */
	DailyReport findByDate(Date date, Integer userId);

	/**
	 * ユーザIdで1件検索を行うメソッド.
	 * 
	 * @param userId
	 * @return 日報情報
	 */
	DailyReport findByUserId(Integer userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table daily_Report
	 *
	 * @mbggenerated Tue Dec 01 15:39:47 JST 2020
	 */
	int countByExample(DailyReportExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table daily_Report
	 *
	 * @mbggenerated Tue Dec 01 15:39:47 JST 2020
	 */
	int deleteByExample(DailyReportExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table daily_Report
	 *
	 * @mbggenerated Tue Dec 01 15:39:47 JST 2020
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table daily_Report
	 *
	 * @mbggenerated Tue Dec 01 15:39:47 JST 2020
	 */
	int insert(DailyReport record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table daily_Report
	 *
	 * @mbggenerated Tue Dec 01 15:39:47 JST 2020
	 */
	int insertSelective(DailyReport record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table daily_Report
	 *
	 * @mbggenerated Tue Dec 01 15:39:47 JST 2020
	 */
	List<DailyReport> selectByExample(DailyReportExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table daily_Report
	 *
	 * @mbggenerated Tue Dec 01 15:39:47 JST 2020
	 */
	DailyReport selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table daily_Report
	 *
	 * @mbggenerated Tue Dec 01 15:39:47 JST 2020
	 */
	int updateByExampleSelective(@Param("record") DailyReport record, @Param("example") DailyReportExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table daily_Report
	 *
	 * @mbggenerated Tue Dec 01 15:39:47 JST 2020
	 */
	int updateByExample(@Param("record") DailyReport record, @Param("example") DailyReportExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table daily_Report
	 *
	 * @mbggenerated Tue Dec 01 15:39:47 JST 2020
	 */
	int updateByPrimaryKeySelective(DailyReport record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table daily_Report
	 *
	 * @mbggenerated Tue Dec 01 15:39:47 JST 2020
	 */
	int updateByPrimaryKey(DailyReport record);
}