package com.example.mapper;

import com.example.domain.DailyReport;
import com.example.domain.DailyReportExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

/**
 * XMLファイル上のSQLを呼び出すクラス(myBatisGeneratorで自動生成)
 * 
 * @author fuka
 *DIコンテナに入れるため、手動でアノテーションを追加
 */
@Mapper
public interface DailyReportMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_reports
     *
     * @mbggenerated Wed Nov 11 00:18:58 JST 2020
     */
    int countByExample(DailyReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_reports
     *
     * @mbggenerated Wed Nov 11 00:18:58 JST 2020
     */
    int deleteByExample(DailyReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_reports
     *
     * @mbggenerated Wed Nov 11 00:18:58 JST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_reports
     *
     * @mbggenerated Wed Nov 11 00:18:58 JST 2020
     */
    int insert(DailyReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_reports
     *
     * @mbggenerated Wed Nov 11 00:18:58 JST 2020
     */
    int insertSelective(DailyReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_reports
     *
     * @mbggenerated Wed Nov 11 00:18:58 JST 2020
     */
    List<DailyReport> selectByExample(DailyReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_reports
     *
     * @mbggenerated Wed Nov 11 00:18:58 JST 2020
     */
    DailyReport selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_reports
     *
     * @mbggenerated Wed Nov 11 00:18:58 JST 2020
     */
    int updateByExampleSelective(@Param("record") DailyReport record, @Param("example") DailyReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_reports
     *
     * @mbggenerated Wed Nov 11 00:18:58 JST 2020
     */
    int updateByExample(@Param("record") DailyReport record, @Param("example") DailyReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_reports
     *
     * @mbggenerated Wed Nov 11 00:18:58 JST 2020
     */
    int updateByPrimaryKeySelective(DailyReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_reports
     *
     * @mbggenerated Wed Nov 11 00:18:58 JST 2020
     */
    int updateByPrimaryKey(DailyReport record);
}