package com.example.mapper;

import com.example.domain.Followings;
import com.example.domain.FollowingsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FollowingsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table followings
     *
     * @mbggenerated Wed Nov 11 00:25:22 JST 2020
     */
    int countByExample(FollowingsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table followings
     *
     * @mbggenerated Wed Nov 11 00:25:22 JST 2020
     */
    int deleteByExample(FollowingsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table followings
     *
     * @mbggenerated Wed Nov 11 00:25:22 JST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table followings
     *
     * @mbggenerated Wed Nov 11 00:25:22 JST 2020
     */
    int insert(Followings record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table followings
     *
     * @mbggenerated Wed Nov 11 00:25:22 JST 2020
     */
    int insertSelective(Followings record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table followings
     *
     * @mbggenerated Wed Nov 11 00:25:22 JST 2020
     */
    List<Followings> selectByExample(FollowingsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table followings
     *
     * @mbggenerated Wed Nov 11 00:25:22 JST 2020
     */
    Followings selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table followings
     *
     * @mbggenerated Wed Nov 11 00:25:22 JST 2020
     */
    int updateByExampleSelective(@Param("record") Followings record, @Param("example") FollowingsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table followings
     *
     * @mbggenerated Wed Nov 11 00:25:22 JST 2020
     */
    int updateByExample(@Param("record") Followings record, @Param("example") FollowingsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table followings
     *
     * @mbggenerated Wed Nov 11 00:25:22 JST 2020
     */
    int updateByPrimaryKeySelective(Followings record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table followings
     *
     * @mbggenerated Wed Nov 11 00:25:22 JST 2020
     */
    int updateByPrimaryKey(Followings record);
}