package com.example.mapper;

import com.example.domain.MonthlyReports;
import com.example.domain.MonthlyReportsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MonthlyReportsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monthly_reports
     *
     * @mbggenerated Wed Nov 11 00:21:20 JST 2020
     */
    int countByExample(MonthlyReportsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monthly_reports
     *
     * @mbggenerated Wed Nov 11 00:21:20 JST 2020
     */
    int deleteByExample(MonthlyReportsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monthly_reports
     *
     * @mbggenerated Wed Nov 11 00:21:20 JST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monthly_reports
     *
     * @mbggenerated Wed Nov 11 00:21:20 JST 2020
     */
    int insert(MonthlyReports record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monthly_reports
     *
     * @mbggenerated Wed Nov 11 00:21:20 JST 2020
     */
    int insertSelective(MonthlyReports record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monthly_reports
     *
     * @mbggenerated Wed Nov 11 00:21:20 JST 2020
     */
    List<MonthlyReports> selectByExample(MonthlyReportsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monthly_reports
     *
     * @mbggenerated Wed Nov 11 00:21:20 JST 2020
     */
    MonthlyReports selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monthly_reports
     *
     * @mbggenerated Wed Nov 11 00:21:20 JST 2020
     */
    int updateByExampleSelective(@Param("record") MonthlyReports record, @Param("example") MonthlyReportsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monthly_reports
     *
     * @mbggenerated Wed Nov 11 00:21:20 JST 2020
     */
    int updateByExample(@Param("record") MonthlyReports record, @Param("example") MonthlyReportsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monthly_reports
     *
     * @mbggenerated Wed Nov 11 00:21:20 JST 2020
     */
    int updateByPrimaryKeySelective(MonthlyReports record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monthly_reports
     *
     * @mbggenerated Wed Nov 11 00:21:20 JST 2020
     */
    int updateByPrimaryKey(MonthlyReports record);
}