package com.example.mapper;

import com.example.domain.MonthlyReport;
import com.example.domain.MonthlyReport;
import com.example.domain.MonthlyReportExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

/**
 * XMLファイル上のSQLを呼び出すクラス(myBatisGeneratorで自動生成)
 * 
 * @author fuka
 *DIコンテナに入れるため、手動でアノテーションを追加
 */
@Mapper
public interface MonthlyReportMapper {
	
	/**
	 * 月報をuserIdで検索するメソッド.
	 * 
	 * @param userId
	 * @return 月報情報
	 */
	MonthlyReport findByUserId(Integer userId);
	
	
	
	
	/**
	 * 月報を日付とユーザーIDで1件検索する
	 * @param date
	 * @param userId
	 * @return
	 */
	MonthlyReport findByDateAndUserId(Integer userId, Integer year, Integer month);

	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monthly_reports
     *
     * @mbggenerated Thu Jan 21 17:21:05 JST 2021
     */
    int countByExample(MonthlyReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monthly_reports
     *
     * @mbggenerated Thu Jan 21 17:21:05 JST 2021
     */
    int deleteByExample(MonthlyReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monthly_reports
     *
     * @mbggenerated Thu Jan 21 17:21:05 JST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monthly_reports
     *
     * @mbggenerated Thu Jan 21 17:21:05 JST 2021
     */
    int insert(MonthlyReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monthly_reports
     *
     * @mbggenerated Thu Jan 21 17:21:05 JST 2021
     */
    int insertSelective(MonthlyReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monthly_reports
     *
     * @mbggenerated Thu Jan 21 17:21:05 JST 2021
     */
    List<MonthlyReport> selectByExample(MonthlyReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monthly_reports
     *
     * @mbggenerated Thu Jan 21 17:21:05 JST 2021
     */
    MonthlyReport selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monthly_reports
     *
     * @mbggenerated Thu Jan 21 17:21:05 JST 2021
     */
    int updateByExampleSelective(@Param("record") MonthlyReport record, @Param("example") MonthlyReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monthly_reports
     *
     * @mbggenerated Thu Jan 21 17:21:05 JST 2021
     */
    int updateByExample(@Param("record") MonthlyReport record, @Param("example") MonthlyReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monthly_reports
     *
     * @mbggenerated Thu Jan 21 17:21:05 JST 2021
     */
    int updateByPrimaryKeySelective(MonthlyReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monthly_reports
     *
     * @mbggenerated Thu Jan 21 17:21:05 JST 2021
     */
    int updateByPrimaryKey(MonthlyReport record);
}