package com.example.mapper;

import com.example.domain.MonthlyReport;
import com.example.domain.MonthlyReportExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

/**
 * XMLファイル上のSQLを呼び出すクラス(myBatisGeneratorで自動生成)
 * 
 * @author fuka
 *DIコンテナに入れるため、手動でアノテーションを追加
 */
@Mapper
public interface MonthlyReportMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monthly_reports
     *
     * @mbggenerated Wed Nov 11 00:21:20 JST 2020
     */
    int countByExample(MonthlyReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monthly_reports
     *
     * @mbggenerated Wed Nov 11 00:21:20 JST 2020
     */
    int deleteByExample(MonthlyReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monthly_reports
     *
     * @mbggenerated Wed Nov 11 00:21:20 JST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monthly_reports
     *
     * @mbggenerated Wed Nov 11 00:21:20 JST 2020
     */
    int insert(MonthlyReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monthly_reports
     *
     * @mbggenerated Wed Nov 11 00:21:20 JST 2020
     */
    int insertSelective(MonthlyReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monthly_reports
     *
     * @mbggenerated Wed Nov 11 00:21:20 JST 2020
     */
    List<MonthlyReport> selectByExample(MonthlyReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monthly_reports
     *
     * @mbggenerated Wed Nov 11 00:21:20 JST 2020
     */
    MonthlyReport selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monthly_reports
     *
     * @mbggenerated Wed Nov 11 00:21:20 JST 2020
     */
    int updateByExampleSelective(@Param("record") MonthlyReport record, @Param("example") MonthlyReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monthly_reports
     *
     * @mbggenerated Wed Nov 11 00:21:20 JST 2020
     */
    int updateByExample(@Param("record") MonthlyReport record, @Param("example") MonthlyReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monthly_reports
     *
     * @mbggenerated Wed Nov 11 00:21:20 JST 2020
     */
    int updateByPrimaryKeySelective(MonthlyReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monthly_reports
     *
     * @mbggenerated Wed Nov 11 00:21:20 JST 2020
     */
    int updateByPrimaryKey(MonthlyReport record);
}