package com.example.mapper;

import com.example.domain.Objectives;
import com.example.domain.ObjectivesExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

/**
 * XMLファイル上のSQLを呼び出すクラス(myBatisGeneratorで自動生成)
 * 
 * @author fuka
 *DIコンテナに入れるため、手動でアノテーションを追加
 */
@Mapper
public interface ObjectivesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table objectives
     *
     * @mbggenerated Wed Nov 11 00:23:40 JST 2020
     */
    int countByExample(ObjectivesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table objectives
     *
     * @mbggenerated Wed Nov 11 00:23:40 JST 2020
     */
    int deleteByExample(ObjectivesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table objectives
     *
     * @mbggenerated Wed Nov 11 00:23:40 JST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table objectives
     *
     * @mbggenerated Wed Nov 11 00:23:40 JST 2020
     */
    int insert(Objectives record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table objectives
     *
     * @mbggenerated Wed Nov 11 00:23:40 JST 2020
     */
    int insertSelective(Objectives record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table objectives
     *
     * @mbggenerated Wed Nov 11 00:23:40 JST 2020
     */
    List<Objectives> selectByExample(ObjectivesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table objectives
     *
     * @mbggenerated Wed Nov 11 00:23:40 JST 2020
     */
    Objectives selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table objectives
     *
     * @mbggenerated Wed Nov 11 00:23:40 JST 2020
     */
    int updateByExampleSelective(@Param("record") Objectives record, @Param("example") ObjectivesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table objectives
     *
     * @mbggenerated Wed Nov 11 00:23:40 JST 2020
     */
    int updateByExample(@Param("record") Objectives record, @Param("example") ObjectivesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table objectives
     *
     * @mbggenerated Wed Nov 11 00:23:40 JST 2020
     */
    int updateByPrimaryKeySelective(Objectives record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table objectives
     *
     * @mbggenerated Wed Nov 11 00:23:40 JST 2020
     */
    int updateByPrimaryKey(Objectives record);
}