package com.example.mapper;

import com.example.domain.Objective;
import com.example.domain.ObjectiveExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

/**
 * XMLファイル上のSQLを呼び出すクラス(myBatisGeneratorで自動生成)
 * 
 * @author fuka
 *DIコンテナに入れるため、手動でアノテーションを追加
 */
@Mapper
public interface ObjectiveMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table objectives
     *
     * @mbggenerated Wed Nov 11 00:23:40 JST 2020
     */
    int countByExample(ObjectiveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table objectives
     *
     * @mbggenerated Wed Nov 11 00:23:40 JST 2020
     */
    int deleteByExample(ObjectiveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table objectives
     *
     * @mbggenerated Wed Nov 11 00:23:40 JST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table objectives
     *
     * @mbggenerated Wed Nov 11 00:23:40 JST 2020
     */
    int insert(Objective record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table objectives
     *
     * @mbggenerated Wed Nov 11 00:23:40 JST 2020
     */
    int insertSelective(Objective record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table objectives
     *
     * @mbggenerated Wed Nov 11 00:23:40 JST 2020
     */
    List<Objective> selectByExample(ObjectiveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table objectives
     *
     * @mbggenerated Wed Nov 11 00:23:40 JST 2020
     */
    Objective selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table objectives
     *
     * @mbggenerated Wed Nov 11 00:23:40 JST 2020
     */
    int updateByExampleSelective(@Param("record") Objective record, @Param("example") ObjectiveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table objectives
     *
     * @mbggenerated Wed Nov 11 00:23:40 JST 2020
     */
    int updateByExample(@Param("record") Objective record, @Param("example") ObjectiveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table objectives
     *
     * @mbggenerated Wed Nov 11 00:23:40 JST 2020
     */
    int updateByPrimaryKeySelective(Objective record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table objectives
     *
     * @mbggenerated Wed Nov 11 00:23:40 JST 2020
     */
    int updateByPrimaryKey(Objective record);
}