package com.example.mapper;

import com.example.domain.Todo;
import com.example.domain.TodoExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

/**
 * XMLファイル上のSQLを呼び出すクラス(myBatisGeneratorで自動生成)
 * 
 * @author fuka
 *DIコンテナに入れるため、手動でアノテーションを追加
 */
@Mapper
public interface TodoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todoes
     *
     * @mbggenerated Wed Nov 11 00:15:42 JST 2020
     */
    int countByExample(TodoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todoes
     *
     * @mbggenerated Wed Nov 11 00:15:42 JST 2020
     */
    int deleteByExample(TodoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todoes
     *
     * @mbggenerated Wed Nov 11 00:15:42 JST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todoes
     *
     * @mbggenerated Wed Nov 11 00:15:42 JST 2020
     */
    int insert(Todo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todoes
     *
     * @mbggenerated Wed Nov 11 00:15:42 JST 2020
     */
    int insertSelective(Todo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todoes
     *
     * @mbggenerated Wed Nov 11 00:15:42 JST 2020
     */
    List<Todo> selectByExample(TodoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todoes
     *
     * @mbggenerated Wed Nov 11 00:15:42 JST 2020
     */
    Todo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todoes
     *
     * @mbggenerated Wed Nov 11 00:15:42 JST 2020
     */
    int updateByExampleSelective(@Param("record") Todo record, @Param("example") TodoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todoes
     *
     * @mbggenerated Wed Nov 11 00:15:42 JST 2020
     */
    int updateByExample(@Param("record") Todo record, @Param("example") TodoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todoes
     *
     * @mbggenerated Wed Nov 11 00:15:42 JST 2020
     */
    int updateByPrimaryKeySelective(Todo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todoes
     *
     * @mbggenerated Wed Nov 11 00:15:42 JST 2020
     */
    int updateByPrimaryKey(Todo record);
}