package com.example.mapper;

import com.example.domain.Todoes;
import com.example.domain.TodoesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TodoesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todoes
     *
     * @mbggenerated Tue Dec 01 15:32:47 JST 2020
     */
    int countByExample(TodoesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todoes
     *
     * @mbggenerated Tue Dec 01 15:32:47 JST 2020
     */
    int deleteByExample(TodoesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todoes
     *
     * @mbggenerated Tue Dec 01 15:32:47 JST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todoes
     *
     * @mbggenerated Tue Dec 01 15:32:47 JST 2020
     */
    int insert(Todoes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todoes
     *
     * @mbggenerated Tue Dec 01 15:32:47 JST 2020
     */
    int insertSelective(Todoes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todoes
     *
     * @mbggenerated Tue Dec 01 15:32:47 JST 2020
     */
    List<Todoes> selectByExample(TodoesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todoes
     *
     * @mbggenerated Tue Dec 01 15:32:47 JST 2020
     */
    Todoes selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todoes
     *
     * @mbggenerated Tue Dec 01 15:32:47 JST 2020
     */
    int updateByExampleSelective(@Param("record") Todoes record, @Param("example") TodoesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todoes
     *
     * @mbggenerated Tue Dec 01 15:32:47 JST 2020
     */
    int updateByExample(@Param("record") Todoes record, @Param("example") TodoesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todoes
     *
     * @mbggenerated Tue Dec 01 15:32:47 JST 2020
     */
    int updateByPrimaryKeySelective(Todoes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todoes
     *
     * @mbggenerated Tue Dec 01 15:32:47 JST 2020
     */
    int updateByPrimaryKey(Todoes record);
}