package com.example.mapper;

import com.example.domain.Todoes;
import com.example.domain.TodoesExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

/**
 * XMLファイル上のSQLを呼び出すクラス(myBatisGeneratorで自動生成)
 * 
 * @author fuka
 *DIコンテナに入れるため、手動でアノテーションを追加
 */
@Mapper
public interface TodoesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todoes
     *
     * @mbggenerated Wed Nov 11 00:15:42 JST 2020
     */
    int countByExample(TodoesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todoes
     *
     * @mbggenerated Wed Nov 11 00:15:42 JST 2020
     */
    int deleteByExample(TodoesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todoes
     *
     * @mbggenerated Wed Nov 11 00:15:42 JST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todoes
     *
     * @mbggenerated Wed Nov 11 00:15:42 JST 2020
     */
    int insert(Todoes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todoes
     *
     * @mbggenerated Wed Nov 11 00:15:42 JST 2020
     */
    int insertSelective(Todoes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todoes
     *
     * @mbggenerated Wed Nov 11 00:15:42 JST 2020
     */
    List<Todoes> selectByExample(TodoesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todoes
     *
     * @mbggenerated Wed Nov 11 00:15:42 JST 2020
     */
    Todoes selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todoes
     *
     * @mbggenerated Wed Nov 11 00:15:42 JST 2020
     */
    int updateByExampleSelective(@Param("record") Todoes record, @Param("example") TodoesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todoes
     *
     * @mbggenerated Wed Nov 11 00:15:42 JST 2020
     */
    int updateByExample(@Param("record") Todoes record, @Param("example") TodoesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todoes
     *
     * @mbggenerated Wed Nov 11 00:15:42 JST 2020
     */
    int updateByPrimaryKeySelective(Todoes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todoes
     *
     * @mbggenerated Wed Nov 11 00:15:42 JST 2020
     */
    int updateByPrimaryKey(Todoes record);
}